import { Roboto} from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],weights: [400, 500, 700],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className} >
        <main className=" max-w-5xl mx-auto px-4 py-8 " >
        {children}
        </main>
      </body>
    </html>
  );
}